name: Docker

on:
  workflow_call:

jobs:

  docker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: setup Docker build
        uses: docker/setup-buildx-action@v3.3.0

      - name: Download a Build Artifact
        uses: actions/download-artifact@v4.1.7
        with:
    # Name of the artifact to download. If unspecified, all artifacts for the run are downloaded.
         name: programa
  
      - name: Docker Login
  # You may pin to the exact commit or the version.
  # uses: docker/login-action@0d4c9c5ea7693da7b068278f7b52bda2a190a446
        uses: docker/login-action@v3.2.0
        with:
    # Username used to log against the Docker registry
         username: jefersow951
    # Password or personal access token used to log against the Docker registry
         password: ${{ secrets.PASSWORD_DOCKERHUB }}


      - name: Build and push Docker images
  # You may pin to the exact commit or the version.
  # uses: docker/build-push-action@94f8f8c2eec4bc3f1d78c1755580779804cb87b2
        uses: docker/build-push-action@v6.0.1
        with:
          context: .
    # Path to the Dockerfile
          file: ./Dockerfile
          push: true
      # List of tags
          tags: jefersow951/go_ci:${{github.ref_name}}
  
          
          
